/**
 * Foundry site generator — first-party `site.generate` fallback backed by the
 * Anthropic Messages API.
 *
 * Lovable (priority 1) needs an operator-produced OAuth token that does not
 * exist yet, which honestly blocks `site.generate` and stops the operating
 * loop at `build`. This adapter is a real fallback, not a fabricated one: a
 * strict `emit_files` tool call on `claude-sonnet-5` produces actual
 * storefront files, the calling service persists them, and production hosting
 * remains Render (see SITE_HOSTING_NOTE in packages/services/src/site/build.ts).
 * `deployProject` therefore returns `{ url: null }` — this generator has no
 * preview hosting and never invents a URL.
 *
 * Generated files are cached in memory per project id. That is sufficient
 * because `SiteBuildService.generate` reads and persists the files in the same
 * call that created the project; a restarted worker replays the recorded
 * result from the idempotency ledger, not from this cache.
 */

import { randomUUID } from 'node:crypto';
import Anthropic from '@anthropic-ai/sdk';
import {
  FoundryError,
  ProviderAuthError,
  ProviderContractError,
  ProviderUnavailableError,
  RateLimitError,
  ValidationError,
} from '@foundry/core';
import { z } from 'zod';
import { ProviderAdapter, type AdapterContext, type ProbeResult } from '../http/adapter.js';
import { FOUNDRY_SITEGEN_MANIFEST, SECRETS } from '../manifests.js';

/** Cheapest real call for the probe, mirroring AnthropicAdapter.probe(). */
const PROBE_MODEL = 'claude-haiku-4-5';
/** Whole-storefront generation needs a strong model and a large output budget. */
export const SITEGEN_GENERATION_MODEL = 'claude-sonnet-5';
export const SITEGEN_MAX_OUTPUT_TOKENS = 60_000;

export const EMIT_FILES_TOOL_NAME = 'emit_files';

const EMIT_FILES_TOOL: Anthropic.Tool = {
  type: 'custom',
  name: EMIT_FILES_TOOL_NAME,
  description:
    'Emit the complete storefront as static files. Call exactly once with every file — full contents, not diffs.',
  strict: true,
  input_schema: {
    type: 'object',
    additionalProperties: false,
    required: ['files'],
    properties: {
      files: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['path', 'content'],
          properties: {
            path: { type: 'string' },
            content: { type: 'string' },
          },
        },
      },
    },
  },
};

const SYSTEM_PROMPT = [
  'You are a senior web engineer generating a complete, production-quality single-page storefront.',
  'Emit the whole site through the emit_files tool in a single call:',
  '- index.html is required, with inline CSS and minimal vanilla JavaScript.',
  '- You may optionally split out styles.css and/or app.js. Never more than 5 files total.',
  '- No external build step: no bundlers, no package.json, no framework imports. Files must be servable as-is by a static host.',
  '- The result must be accessible (semantic landmarks, labelled controls, sufficient contrast), responsive across mobile and desktop, and visually modern.',
  'The user message contains the site specification JSON. Generate real content from it; do not invent orders, analytics, or placeholder lorem ipsum.',
].join('\n');

/** Relative, no `..` segments, no empty segments — a path we can safely persist. */
function isSafeRelativePath(path: string): boolean {
  if (path.startsWith('/') || /^[A-Za-z]:/.test(path)) return false;
  return path.split(/[\\/]/).every((segment) => segment.length > 0 && segment !== '..');
}

const EmittedFilesSchema = z.object({
  files: z
    .array(
      z.object({
        path: z
          .string()
          .min(1)
          .refine(isSafeRelativePath, { message: 'path must be relative and must not contain ".." segments' }),
        content: z.string().min(1),
      }),
    )
    .min(1, 'emit_files returned zero files'),
});

/**
 * Minimal Messages surface this adapter consumes. Tests inject a fake through
 * the constructor override so no live call is ever made; production constructs
 * the real SDK client lazily from the secret store.
 */
export interface SitegenMessagesClient {
  readonly messages: {
    create(params: Anthropic.MessageCreateParamsNonStreaming): Promise<Anthropic.Message>;
  };
}

export class FoundrySitegenAdapter extends ProviderAdapter {
  override readonly manifest = FOUNDRY_SITEGEN_MANIFEST;
  #client: SitegenMessagesClient | undefined;
  /** projectId → { path → content } for projects generated by this instance. */
  readonly #projects = new Map<string, Record<string, string>>();

  constructor(ctx: AdapterContext, overrides?: { readonly client?: SitegenMessagesClient }) {
    super(ctx);
    this.#client = overrides?.client;
  }

  #anthropic(): SitegenMessagesClient {
    if (this.#client) return this.#client;
    const secret = this.requireSecret(SECRETS.anthropicApiKey);
    this.#client = new Anthropic({
      apiKey: secret.reveal(),
      // Retry, backoff and breaker behaviour is owned by the platform, exactly
      // as in the Anthropic adapter; SDK retries would multiply attempts.
      maxRetries: 0,
      timeout: 10 * 60_000,
    });
    return this.#client;
  }

  override async probe(): Promise<ProbeResult> {
    const started = Date.now();
    const response = await this.#call('messages.create', () =>
      this.#anthropic().messages.create({
        model: PROBE_MODEL,
        max_tokens: 1,
        messages: [{ role: 'user', content: 'ok' }],
      }),
    );
    return {
      succeeded: true,
      detail: `POST /v1/messages accepted (model ${response.model}, stop_reason ${response.stop_reason})`,
      evidence: {
        endpoint: 'POST /v1/messages',
        model: response.model,
        stopReason: response.stop_reason,
        inputTokens: response.usage.input_tokens,
        latencyMs: Date.now() - started,
      },
    };
  }

  /**
   * Generates the storefront now — one strict tool-use call, files validated
   * and cached under a fresh project id. `input.initialMessage` carries the
   * site spec JSON assembled by SiteBuildService.
   */
  async createProject(input: {
    readonly initialMessage: string;
    readonly idempotencyKey: string;
    readonly wait: boolean;
  }): Promise<{ projectId: string }> {
    this.assertActivated();
    const files = await this.#emitFiles([{ role: 'user', content: input.initialMessage }]);
    const projectId = `sitegen_${randomUUID()}`;
    this.#projects.set(projectId, files);
    return { projectId };
  }

  /** Revises a generated project by re-emitting the complete file set. */
  async sendMessage(input: { readonly projectId: string; readonly message: string; readonly wait: boolean }): Promise<void> {
    this.assertActivated();
    const current = this.#filesFor(input.projectId);
    const revisionPrompt = [
      'Revise the storefront below. Apply the revision request, then re-emit the COMPLETE file set via emit_files — every file, full contents, not a diff.',
      `Revision request:\n${input.message}`,
      `Current files:\n${JSON.stringify(current)}`,
    ].join('\n\n');
    const files = await this.#emitFiles([{ role: 'user', content: revisionPrompt }]);
    this.#projects.set(input.projectId, files);
  }

  async listFiles(projectId: string): Promise<string[]> {
    this.assertActivated();
    return Object.keys(this.#filesFor(projectId));
  }

  async readFile(projectId: string, path: string, _ref?: string): Promise<string> {
    this.assertActivated();
    const files = this.#filesFor(projectId);
    const content = files[path];
    if (content === undefined) {
      throw new Error(
        `foundry_sitegen project "${projectId}" has no file "${path}". Known files: ${Object.keys(files).join(', ')}`,
      );
    }
    return content;
  }

  /**
   * This generator has no preview hosting; production hosting is Render (see
   * SITE_HOSTING_NOTE in packages/services/src/site/build.ts). A fabricated
   * URL here would be recorded as a preview that does not exist.
   */
  async deployProject(_projectId: string): Promise<{ url: null }> {
    return { url: null };
  }

  #filesFor(projectId: string): Record<string, string> {
    const files = this.#projects.get(projectId);
    if (!files) {
      throw new Error(
        `foundry_sitegen knows no project "${projectId}". Generated projects live in memory for the build that ` +
          'created them; re-run generation rather than inventing files.',
      );
    }
    return files;
  }

  async #emitFiles(messages: Anthropic.MessageParam[]): Promise<Record<string, string>> {
    const response = await this.#call('messages.create', () =>
      this.#anthropic().messages.create({
        model: SITEGEN_GENERATION_MODEL,
        max_tokens: SITEGEN_MAX_OUTPUT_TOKENS,
        system: SYSTEM_PROMPT,
        messages,
        tools: [EMIT_FILES_TOOL],
        tool_choice: { type: 'tool', name: EMIT_FILES_TOOL_NAME },
      }),
    );

    // Refusal is checked before content is read: the classifiers can decline
    // pre-output and return an empty content array.
    if (response.stop_reason === 'refusal') {
      const details = (response as { stop_details?: { category?: string; explanation?: string } }).stop_details;
      throw new ValidationError(
        `foundry_sitegen: the model declined to generate the storefront (${details?.category ?? 'unspecified'})`,
        { category: details?.category ?? null, explanation: details?.explanation ?? null },
      );
    }

    const toolUse = response.content.find(
      (block): block is Anthropic.ToolUseBlock => block.type === 'tool_use' && block.name === EMIT_FILES_TOOL_NAME,
    );
    if (!toolUse) {
      throw new ProviderContractError(
        'foundry_sitegen',
        `the model returned no ${EMIT_FILES_TOOL_NAME} tool call despite forced tool_choice`,
        { stopReason: response.stop_reason },
      );
    }

    const parsed = EmittedFilesSchema.safeParse(toolUse.input);
    if (!parsed.success) {
      throw new ProviderContractError(
        'foundry_sitegen',
        `${EMIT_FILES_TOOL_NAME} input failed validation: ${parsed.error.message}`,
        { issues: parsed.error.issues.slice(0, 10) },
      );
    }

    const files: Record<string, string> = {};
    for (const file of parsed.data.files) files[file.path] = file.content;
    return files;
  }

  async #call<T>(operation: string, fn: () => Promise<T>): Promise<T> {
    try {
      return await fn();
    } catch (error) {
      throw this.#translate(operation, error);
    }
  }

  /** Same minimal translation as the Anthropic adapter, for this provider id. */
  #translate(operation: string, error: unknown): Error {
    // Never re-wrap a FoundryError — that would destroy its category.
    if (error instanceof FoundryError) return error;
    if (error instanceof Anthropic.APIConnectionError) {
      return new ProviderUnavailableError('foundry_sitegen', `${operation}: ${error.message}`, { operation });
    }
    if (error instanceof Anthropic.RateLimitError) {
      const retryAfter = Number(error.headers?.get?.('retry-after') ?? '');
      return new RateLimitError('foundry_sitegen', Number.isFinite(retryAfter) ? retryAfter : undefined, { operation });
    }
    if (error instanceof Anthropic.AuthenticationError || error instanceof Anthropic.PermissionDeniedError) {
      return new ProviderAuthError('foundry_sitegen', error.message, { operation, status: error.status });
    }
    if (error instanceof Anthropic.InternalServerError) {
      // Includes 529 overloaded_error, which is retryable.
      return new ProviderUnavailableError('foundry_sitegen', error.message, { operation, status: error.status });
    }
    if (error instanceof Anthropic.BadRequestError || error instanceof Anthropic.NotFoundError) {
      return new ValidationError(`Anthropic rejected ${operation}: ${error.message}`, {
        operation,
        status: error.status,
      });
    }
    if (error instanceof Anthropic.APIError) {
      return new ProviderContractError('foundry_sitegen', `${operation}: ${error.message}`, {
        operation,
        status: (error as { status?: number }).status,
      });
    }
    return new ProviderUnavailableError('foundry_sitegen', `${operation}: ${String(error)}`, { operation });
  }
}
